server:
  port: 10084
  servlet:
    context-path: /xxl-job-admin
spring:
  boot:
    admin:
      client:
        instance:
          service-url: http://127.0.0.1:10083
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/calm-job?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: E/v2nQHfRFE7LNQ192WzEO2Cl1w2hu/M
  #nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          management:
            # 参考：https://blog.csdn.net/weixin_41767181/article/details/106075472
            context-path: ${server.servlet.context-path}/actuator
      config:
        # 参考：https://blog.csdn.net/weixin_41767181/article/details/106075472
        context-path: ${server.servlet.context-path}/actuator
  #redis
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 10000
        min-idle: 3
    password:
    port: 6379
    timeout: 50000
