<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.calm</groupId>
    <artifactId>calm-cloud</artifactId>
    <version>${revision}</version>

    <packaging>pom</packaging>
    <description>Calm-Springboot、SpringCloud、SpringCloudAlibaba、Mybatis-plus、Openfeign</description>

    <properties>
        <!--当前工程中的所有模块，版本统一进行控制-->
        <revision>4.0.0</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>21</java.version>

        <spring-boot.version>3.2.12</spring-boot.version>
        <spring-cloud.version>2023.0.5</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.3.2</spring-cloud-alibaba.version>

        <openfeign.version>4.2.0</openfeign.version>

        <knife4j.version>4.5.0</knife4j.version>

        <mybatis-plus.version>3.5.9</mybatis-plus.version>
        <pagehelper.version>2.1.0</pagehelper.version>
        <dynamic-datasource.version>4.3.1</dynamic-datasource.version>
        <druid-spring-boot.version>1.2.24</druid-spring-boot.version>
        <mysql.version>9.1.0</mysql.version>

        <slf4j-api.version>2.0.0</slf4j-api.version>

        <jasypt.version>3.0.5</jasypt.version>
        <hutool.version>5.8.35</hutool.version>
        <velocity.version>2.4.1</velocity.version>

    </properties>

    <!--聚合-为了在打包的时候可以使用父工程可直接对子工程进行打包-->
    <modules>
        <module>calm-common-bom</module>
        <module>calm-gateway</module>
        <module>calm-sequence</module>
        <module>calm-user</module>
        <module>calm-web</module>
    </modules>

    <!--项目中最基本的依赖导入-->
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.36</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-api.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <!--
    dependencyManagement 的作用： 能让所有子项目中引用一个依赖而不用显式的声明版本号，maven会沿着父子层的向上走，直至找到一个dependencyManagement元素的项目，
    然后使用其元素中指定的版本号，
        1、只用来声明版本号，并不引入具体实现，因此子项目中需要声明需要使用到的依赖
        2、如果不在子项目中声明依赖，是不会从父项目中继承下来的，只有在子项目中写了该依赖，并且没有指定版本号，才会从父工程的dependencyManagement中继承该项，并且version和scope都会读取父工程的
        3、如果子项目中指定了版本号，那么会使用子项目中所指定的版本号
    -->
    <dependencyManagement>
        <dependencies>
            <!--此工程中的子工程-->
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-common-utils</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-common-nacos</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-common-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-common-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-gateway</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-user</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-sequence</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.calm</groupId>
                <artifactId>calm-job</artifactId>
                <version>${revision}</version>
            </dependency>

            <!--swagger-start-->
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-dependencies</artifactId>
                <version>${knife4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--swagger-end-->
            <!--代码模板-->
            <dependency>
                <groupId>org.apache.velocity</groupId>
                <artifactId>velocity-engine-core</artifactId>
                <version>${velocity.version}</version>
            </dependency>
            <!--密文密码-->
            <dependency>
                <groupId>com.github.ulisesbocchio</groupId>
                <artifactId>jasypt-spring-boot-starter</artifactId>
                <version>${jasypt.version}</version>
            </dependency>
            <!--连接数据库-->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid-spring-boot.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
            </dependency>
            <!--mybatis-plus动态数据源-->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
                <version>${dynamic-datasource.version}</version>
            </dependency>
            <!--openfeign-->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-openfeign</artifactId>
                <version>${openfeign.version}</version>
            </dependency>
            <!--导入了springboot、springcloud、springcloudalibaba-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--spring cloud alibaba-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <build>
        <finalName>${project.artifactId}</finalName>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </resource>
        </resources>
        <pluginManagement>
            <plugins>
                <!--maven-compiler-plugin插件可以指定项目源码的jdk版本，编译后的jdk版本，以及编码。-->
                <!-- 参考: https://blog.csdn.net/liupeifeng3514/article/details/80236077 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <testSource>${java.version}</testSource>
                        <testTarget>${java.version}</testTarget>
                        <encoding>UTF-8</encoding>
                        <compilerArgs>
                            <compilerArg>
                                -parameters
                            </compilerArg>
                        </compilerArgs>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.1</version>
                    <configuration>
                        <encoding>UTF-8</encoding>
                    </configuration>
                </plugin>
                <!--maven-source-plugin 这个插件专门负责将项目源文件打成包的-->
                <!--参考: https://blog.csdn.net/liaowenxiong/article/details/124879376 -->
                <!--提供项目自动将源码打包并发布的功能, maven会自动将source install到repository -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.3.1</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <!-- 执行生命周期阶段 verify 时会调用该插件的目标 jar-no-fork，该目标会将 jar 文件安装到本地的 Maven 仓库中。 -->
                            <phase>verify</phase>
                            <goals>
                                <!--在生命周期后执行绑定的source插件的goals -->
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.4.2</version>
                    <configuration>
                        <archive>
                            <!-- 生成的jar中，包含pom.xml和pom.properties这两个文件 -->
                            <addMavenDescriptor>true</addMavenDescriptor>
                            <!-- 生成MANIFEST.MF的设置 -->
                            <manifest>
                                <!--这个属性特别关键，如果没有这个属性，有时候我们引用的包maven库
                                下面可能会有多个包，并且只有一个是正确的，其余的可能是带时间戳的，
                                此时会在classpath下面把那个带时间戳的给添加上去，
                                然后我们 在依赖打包的时候，打的是正确的，所以两头会对不上，报错。 -->
                                <useUniqueVersions>false</useUniqueVersions>
                                <!-- 为依赖包添加路径, 这些路径会写在MANIFEST文件的Class-Path下 -->
                                <addClasspath>true</addClasspath>
                                <!-- 这个jar所依赖的jar包添加classPath的时候的前缀，如果这个jar本身
                                和依赖包在同一级目录，则不需要添加 -->
                                <classpathPrefix>lib/</classpathPrefix>
                            </manifest>
                        </archive>
                    </configuration>
                </plugin>
                <!--springboot启动类的jar包-->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <!--
                    配置参考：
                    https://blog.csdn.net/tian830937/article/details/119525273
                    -->
                    <configuration>
                        <addResources>true</addResources>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
