server:
  port: 10088
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:12848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
