<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.calm</groupId>
        <artifactId>calm-cloud</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>calm-web</artifactId>

    <description>CalmWeb-layui前端页面、跳转页面配置</description>

    <properties>

    </properties>

    <dependencies>
        <dependency>
            <groupId>com.calm</groupId>
            <artifactId>calm-common-nacos</artifactId>
        </dependency>
        <dependency>
            <groupId>com.calm</groupId>
            <artifactId>user-api</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>


    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <!--springboot启动类的jar包-->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>


</project>
