server:
  port: 10083
spring:
  #admin监控
  boot:
    admin:
      notify:
        mail:
          from: qjyn1314@163.com
          to: qjyn1314@foxmail.com
      client:
        instance:
          prefer-ip: true
  #nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
  #redis
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 10000
        min-idle: 3
    password:
    port: 6379
    timeout: 50000
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: qjyn1314@163.com
    password: ENC@[nM+/DFGNERlrYjduKijMdnPA2e8VpP/4Ws97IfuNk28XoR2oyRWVZA==]
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
