spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
#        group: DEV_GROUP  #默认是  DEFAULT_GROUP
#        namespace: 2f942653-3980-418d-95ed-f36cd44ac984   #默认是public 如果需要使用，则需要将nacos中所创建出来的命名空间中命名空间ID
      discovery:
        server-addr: 127.0.0.1:8848
#        group: DEV_GROUP  #默认是  DEFAULT_GROUP
#        namespace: 2f942653-3980-418d-95ed-f36cd44ac984   #默认是public 如果需要使用，则需要将nacos中所创建出来的命名空间中命名空间ID



