spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
      discovery:
        locator:
          enabled: true
      routes:
        - id: calm_order
          uri: lb://calm-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: calm_web
          uri: lb://calm-web
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1
