spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  boot:
    admin:
      client:
        connect-timeout: 5000
        instance:
          service-url: http://127.0.0.1:84
        period: 10000
        read-timeout: 5000

  security:
    user:
      name: user
      password: 123456