<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.calm</groupId>
        <artifactId>calm-cloud</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>calm-user</artifactId>

    <packaging>pom</packaging>

    <description>CalmUser-用户服务</description>

    <properties>

    </properties>

    <modules>
        <module>user-api</module>
        <module>user-service</module>
    </modules>

    <dependencies>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
    </build>


</project>
